// Unicode font (Noto Sans Regular - Base64)
const NotoSansBase64 = `
AAEAAAALAIAAAwAwT1MvMg8SBJQAAAC8AAAAYGNtYXAWG+QpAAABHAAAAFRnYXNwAAAAEAAAAYAAAAAIZ2x5Zr8mXrAAAAGQAAABoGhlYWQW8A2KAAABuAAAADZoaGVhBfgCygAAAcwAAAAkaG10eAAXABgAAAHwAAAAGGxvY2EAAABKAAACFAAAAAxtYXhwAAkAEAAAAlAAAAAgbmFtZc6pXnEAAAJkAAABknBvc3QAAwAAAAAD6AAAACBwcmVwAAEAAAAABAAAAAEAAQAA
`; 
// ↑↑ Replace this BASE64 with the FULL base64 from the tool

export default NotoSansBase64;
